---
title: "Code for Parkinson's dataset"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# clean the environment and 
rm(list = ls())
# run all helper functions
source("../Functions.R")
source("../sim_helper.R")
```

```{r}
### NEED TO RUN ALL CODE ONCE BEFORE USING
# To load the data again
load("Parkn.RData")
```


# Load the data

```{r}
data(Franchini2012) # Transform data from arm-based format to contrast-based format 
p1 <- pairwise(list(Treatment1, Treatment2, Treatment3), n = list(n1, n2, n3), mean = list(y1, y2, y3), sd = list(sd1, sd2, sd3), data = Franchini2012, studlab = Study) 
p1
```

```{r}
# find the multi-arm study
p_study = multi_study(p1)
p_study
```

```{r}
# calculate the covariance for the multi-arm study
cov_Guttman1997 = (0.6990666^2 + 0.6949881^2 - 0.7177460^2)/2
cov_Guttman1997
```


```{r}
# keep only the 2 arms studies
pksn_multi = p1[-3, 1:5]
pksn_multi[order(pksn_multi$studlab),]
```

```{r}
pksn_multi
```


# Model

```{r}
# matrix with all var on diagonal
var_cov = diag((pksn_multi$seTE)^2)
# find the indexes that stands for multi-arm 
multi_index = which(pksn_multi$studlab == unique(as.vector(p_study$studlab)))
# update the cov terms in the var_cov matrix 
var_cov[multi_index[1],multi_index[2]] = cov_Guttman1997
var_cov[multi_index[2],multi_index[1]] = cov_Guttman1997

# better visualization
t = data.frame(var_cov)
```


```{r}
# Choleski Decomposition of var_cov matrix
D = chol(solve(var_cov))
# wight = D
w = D
w
```





```{r}
y = pksn_multi$TE

# X ('plac' as reference)
X =  X_matrix(pksn_multi$treat1, pksn_multi$treat2, ref = "Placebo", 
              n = 5) # n is the total number of distinct treatments

n = length(y)
K = ncol(X)
```


```{r}
gr <- graph(c(1,2,1,3,1,4,2,3,2,4,3,4), directed=FALSE)
plot(gr)
```

```{r}
### DEFAULT WAY OF DRAWING THE COORDINATE PATH
#   (the red line represents lambda where the paths are separated)
# gr is needed
fit = fusedlasso(y=w%*%y, X=w%*%X, graph = gr, gamma=1)
fusedLasso_gr(fit)
```



# AICc summary 
```{r}
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)
#min_row = max(which(sum_table_a$AICc == min(sum_table_a$AICc)))

sub_sum = data.frame()
for (i in 0:K){
  # select all rows that have df == i
  sub_df_i = filter(sum_table_a, df == i)
  # find row(s) that has the smallest rss
  sub_df_minRSS = filter(sub_df_i, rss == min(rss))
  # if there are several rows, choose the one has the smallest lambda
  sub_add = filter(sub_df_minRSS, lambda == min(lambda))
  # add into the summary table
  sub_sum = rbind(sub_sum, sub_add)
}
rownames(sub_sum) = 1:(K + 1)

# add delta_AIC
ref = min(sub_sum$AICc)
sub_sum$delta_AICc = sub_sum$AICc - ref
sub_sum
```


```{r}
# create a table that only include the first row of df = 0 
#   with all other rows 
tt = data.frame(sum_table_a)[which(sum_table_a$df != 0),]
tt = rbind(sum_table_a[which(sum_table_a$df != 0)[1] - 1, ], tt)
ref = min(tt$AICc)
tt$delta_AICc = tt$AICc - ref
round(tt,1)
```


```{r}
### DRAWING THE COORDINATE PATH BY COODING
#   (the red line represent the best lambda under AICc)

# Create a new fit_plot object with a row of 0's for ref trt
fit_plot <- fit
fit_plot$beta <- rbind(rep(0,  dim(fit_plot$beta)[2]), fit_plot$beta)
fit_plot$bls <- c(0, fit_plot$bls)


p_matrix<- rbind(t(fit_plot$beta), fit_plot$bls)
x <- c(0, rev(fit_plot$lambda))

data <- data.frame(x = rep(x, ncol(p_matrix)), 
                   value=rev(as.numeric(p_matrix)), 
                   treatment=rep(paste0('', rev(1:ncol(p_matrix))), each=length(x)))

# reorder the legend
data$treatment <- factor(data$treatment, levels = c(1,5,2,3,4))

ggplot(data = data, aes(x=x, y=value)) + 
  geom_line(aes(colour=treatment))+                            
  geom_vline(xintercept = rev(fit_plot$lambda[-12]), linetype="dashed") +
  geom_vline(xintercept = fit_plot$lambda[12], linetype="dashed", color = "red") +
  xlab(expression(lambda)) + ylab("Coordinates of d")
```

```{r}
# save the coordinate path with certain requirements 
ggsave(file = "Parkinson_FusedLasso_multi.eps", dpi = 800, width = 10, height = 4.5, limitsize = FALSE) 
```


# Analysis with 'netmeta' package

```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = p1, sm = "MD", reference = "plac")
netgraph(net)
```


```{r}
# check the fixed-effect model
fit$bls
sum = summary(net)
sum$x
```



```{r}
# the league table with given order of treatments 
t1 = netleague(net,net, digits = 2, seq = c("Placebo", "Ropinirole","Bromocriptine","Cabergoline","Pramipexole"))

# the fix effect model
t2 = t1$fixed
t2
```

```{r}
# calculate the coefficient of variation of treatments 
#   in the same order of the league table
cv_t = data.frame()
for (i in 2:nrow(t2)){
  for (j in 1:(i-1)) {
    a = t2[i,j]
    # transfer the string in the league table into numbers 
    results = league_str_num(a)
    #print(results)
    # calculate the cv
    cv_t[i,j] = ((league_str_num(a)[3] - 
                    league_str_num(a)[2])/4)/league_str_num(a)[1]
  }
}
cv_t
```



```{r}
# beta values of the best model under AICc
ddd <- fit$beta[,12]
# calculate the GFL-NMA estimates of the lowest AICc model
outer(sort(c(0,ddd), decreasing = TRUE),sort(c(0,ddd), decreasing = TRUE),"-")
```


```{r}
# The rankgram of the Parkinson data
set.seed(1)
rank_ = rankogram(net)
rp = plot(rank_)
```


```{r}
# SUCRA values (round in 2 digits)
round(sort(rank_$ranking.fixed),2)
```

# Save some main results for future using 

```{r}
### RUN THIS BEFORE RELOAD THE RESULTS
# Save multiple objects
save(p1, pksn_multi, fit, sum_table_a, net, cv_t, file = "Parkn.RData")
```


# Pooled GFL-NMA
```{r}
###Code for pooled GFL-NMA###
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)
min_row = max(which(sum_table_a$AICc == min(sum_table_a$AICc)))


best_beta = fit$beta[, min_row]
t_group_list = group_dd(best_beta)

# replace the string names by num
pksn = p1[,1:5]
seq = c("Placebo","Bromocriptine","Cabergoline","Pramipexole","Ropinirole")
pksn_ = data.frame(cbind(TE = pksn$TE, seTE = pksn$seTE,
                   studlab = factor(pksn$studlab, labels = 1:7),
                   t1 = match(pksn$treat1,seq), t2 = match(pksn$treat2,seq)))



update = pksn_

# rename treatments that are pooled as the smallest number in the group
c1 = sapply(pksn_$t1, contains, y = 5)
if(any(c1)){update$t1[which(c1)] = 2}

c2 = sapply(pksn_$t2, contains, y = 5)
if(any(c2)){update$t2[which(c2)] = 2}

# drop rows that compare the same treatments (t1=t2)
update = update[-which(update$t1 == update$t2),]

net_i = netmeta(TE, seTE, t1, t2, studlab,data = update, sm = "MD", reference = 1)
group_i = t_group_list

# t1 = netleague(net_i,net_i, digits = 2, seq = c("1", "2", "3", "4"))
#t1

N.treat = 5
smry = summary(net_i)
# est: estimated treatment effects 
est = t_vs_ref(smry$random$TE, N.treat, group_i)


# print the estimated values (TE or corresponding 95% CI)
full_lower = data.frame(matrix(rep(0, N.treat*N.treat), nrow = N.treat))
rownames(full_lower) = colnames(full_lower) = 1:N.treat
# change smry$random$... to change the type of values 
row_names = as.numeric(rownames(data.frame(smry$random$TE)))

row_group_num = 0
for (row in 1:N.treat) {
  for (subgroup in group_i) {
    if(row %in% subgroup){row_group_num = min(subgroup)}
  }
  # no pooled group
  if(row_group_num == 0){row_group_num = row}
  col_group_num = 0
  for (col in 1:N.treat) {
    for (subgroup in group_i) {
      if(col %in% subgroup){col_group_num = min(subgroup)}
    }
    if(col_group_num == 0){col_group_num = col}
    
    c1=which(row_names == row_group_num)
    c2=which(row_names == col_group_num)
    
    full_lower[row,col] = smry$random$TE[c1,c2]
    col_group_num = 0
  }
  row_group_num = 0
}
full_lower
```
















