---
title: "General code"
author: "Sandy Kong"
date: "2023-03-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

```{r}
# To load the data again
load("Parkn.RData")
```


# Muilt-arm study

```{r}
data(Franchini2012) # Transform data from arm-based format to contrast-based format 
p1 <- pairwise(list(Treatment1, Treatment2, Treatment3), n = list(n1, n2, n3), mean = list(y1, y2, y3), sd = list(sd1, sd2, sd3), data = Franchini2012, studlab = Study) 
p1
```

```{r}
# find the multi-arm study
p_study = multi_study(p1)
p_study
```

```{r}
# calculate the covariance for the multi-arm study
cov_Guttman1997 = (0.6990666^2 + 0.6949881^2 - 0.7177460^2)/2
cov_Guttman1997
```


```{r}
# keep only the 2 arms that have placebo as comparator
# pksn_multi = p1[-5, 1:5]
pksn_multi = p1[-3, 1:5]
pksn_multi[order(pksn_multi$studlab),]
```

```{r}
pksn_multi
```



```{r}
# matrix with all var on diagonal
var_cov = diag((pksn_multi$seTE)^2)
# find the indexes that stands for multi-arm 
multi_index = which(pksn_multi$studlab == unique(as.vector(p_study$studlab)))
# update the cov terms in the var_cov matrix 
var_cov[multi_index[1],multi_index[2]] = cov_Guttman1997
var_cov[multi_index[2],multi_index[1]] = cov_Guttman1997

# better visualization
t = data.frame(var_cov)
```


```{r}
# Choleski Decomposition of var_cov matrix
D = chol(solve(var_cov))
# wight = D
w = D
w
```





```{r}
y = pksn_multi$TE

# X ('plac' as reference)
X =  X_matrix(pksn_multi$treat1, pksn_multi$treat2, ref = "Placebo", 
              n = 5) # n is the total number of distinct treatments

n = length(y)
K = ncol(X)
```


```{r}
gr <- graph(c(1,2,1,3,1,4,2,3,2,4,3,4), directed=FALSE)
plot(gr)
```

```{r}
brewer.pal(n = 8, name = "Dark2")
```

```{r}
# gr is needed
fit = fusedlasso(y=w%*%y, X=w%*%X, graph = gr, gamma=1)
fusedLasso_gr(fit)
```
## AICc summary 
```{r}
# from general code, step-by-step shown in the general file 
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)

sub_sum = data.frame()
for (i in 0:K){
  # select all rows that have df == i
  sub_df_i = filter(sum_table_a, df == i)
  # find row(s) that has the smallest rss
  sub_df_minRSS = filter(sub_df_i, rss == min(rss))
  # if there are several rows, choose the one has the smallest lambda
  sub_add = filter(sub_df_minRSS, lambda == min(lambda))
  # add into the summary table
  sub_sum = rbind(sub_sum, sub_add)
}
rownames(sub_sum) = 1:(K + 1)

# Add the weight to the sub summary table 
sub_sum$weight = exp(-0.5 * sub_sum$AICc)/sum(exp(-0.5 * sub_sum$AICc))

# add delta_AIC
ref = min(sub_sum$AICc)
sub_sum$delta_AICc = sub_sum$AICc - ref
sub_sum
```
## BICc summary
```{r}
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, BICc = BICc_rss(rss, Ks)))
rownames(sum_table_a) = 1:nrow(sum_table_a)

sum_table_a
```



```{r}
tt = data.frame(sum_table_a)[which(sum_table_a$df != 0),]
tt = rbind(sum_table_a[which(sum_table_a$df != 0)[1] - 1, ], tt)
ref = min(tt$AICc)
tt$delta_AICc = tt$AICc - ref
tt
```




```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = p1, sm = "MD", reference = "plac")
netgraph(net)
```

-0.4099753 -0.7099753 -1.7792705 -0.3881797 ## solve(var_cov^1/2)
-0.5849614 -0.8849614 -1.7969033 -0.5262000 ## c

After removing row 3 Plac vs Pram, not row 5 
-0.4678992 -0.7678992 -1.8011238 -0.4338672 ## c
-0.5237265 -0.8237265 -2.0518968 -0.4779010 ## solve(var_cov^1/2)

Random approach
-0.5542771 -0.8542771 -1.7609034 -0.4439179

-0.5240 -0.8240 -1.8116 -0.4781 ## netmeta
```{r}
# check the fixed-effect model
fit$bls
sum = summary(net)
sum$x
```


netleague
```{r}
library(writexl)
t1 = netleague(net,net, digits = 2) # writexl=TRUE
t2 = t1$fixed
t2
```

```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = p1, sm = "MD", reference = "plac")
```



```{r}
best_beta = fit$beta[,12]
d12 = best_beta[1]
d13 = best_beta[2]
d14 = best_beta[3]
d15 = best_beta[4]

d23 = d13 - d12
d24 = d14 - d12
d25 = d15 - d12

d34 = d14 - d13
d35 = d15 - d13

d45 = d15 -d14

round(c(d23, d12, d24, d25), 4)
round(c(d13, d34, d35), 4)
round(c(d14, d15), 4)
round(d45,4)
```








rankogram
```{r}
rank_ = rankogram(net)
plot(rank_)
rank_$ranking.common
```



```{r}
# Save multiple objects
save(p1, pksn_multi, fit, sum_table_a, net, file = "Parkn.RData")
```



















