
```{r}
# clean the environment and 
rm(list = ls())
# run all helper functions
source("../Functions.R")
source("../sim_helper.R")
```

```{r}
### NEED TO RUN ALL CODE ONCE BEFORE USING
# To load the data again
load("depression.RData")
```


# Load the data
```{r}
data("depression")
p1 <- pairwise(treat = treatment, n = sampleSize, event = responders, 
               data = depression$data.ab, studlab = study) 
p1
```


```{r}
# find the multi-arm study
d_study = multi_study(p1)
d_study
```

```{r}
set.seed(1)
net = netmeta(TE, seTE, treat1, treat2, studlab, data = p1, sm = "MD", reference = "fluoxetine")

# calculate the covariance for the multi-arm study
cov_Fava2000 = (0.11688166^2 + 0.11796669^2 - 0.14154518^2+ net$tau2)/2
cov_Fava2000
cov_Fava2002 = (0.10268078^2 + 0.09527529^2 - 0.10900747^2+ net$tau2)/2
cov_Fava2002
```

```{r}
# keep only the 2 arms
d_multi = p1[-c(82,86),]
d_multi[order(d_multi$studlab),]
``` 

```{r}
# matrix with all var on diagonal
var_cov = diag((d_multi$seTE)^2)

# Variance-covariant matrix under random effect model
var_cov = var_cov + net$tau2*diag(dim(var_cov)[1]) 

# find the indexes that stands for multi-arm 
multi_index = which(d_multi$studlab == "Fava2000")
# update the cov terms in the var_cov matrix 
var_cov[multi_index[1],multi_index[2]] = cov_Fava2000
var_cov[multi_index[2],multi_index[1]] = cov_Fava2000

multi_index2 = which(d_multi$studlab == "Fava2002")
# update the cov terms in the var_cov matrix 
var_cov[multi_index2[1],multi_index2[2]] = cov_Fava2002
var_cov[multi_index2[2],multi_index2[1]] = cov_Fava2002

# better visualization
t = data.frame(var_cov)
```

```{r}
# Choleski Decomposition of var_cov matrix
D = chol(solve(var_cov))
# wight = D
w = D

y = d_multi$TE

# X ('plac' as reference)
X =  X_matrix(d_multi$treat1, d_multi$treat2, ref = "fluoxetine", 
              n = 12) # n is the total number of distinct treatments

n = length(y)
K = ncol(X)

e = n_treats_graph_generator(12)
gr = graph(e, directed=FALSE)

plot(gr)
```

```{r}
### DEFAULT WAY OF DRAWING THE COORDINATE PATH
#   (the red line represents lambda where the paths are separated)
# gr is needed
fit = fusedlasso(y=w%*%y, X=w%*%X, graph = gr, gamma=1)
fusedLasso_gr(fit)
```

# AICc summary 
```{r}
# from general code, step-by-step shown in the general file 
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)

sub_sum = data.frame()
for (i in 0:K){
  # select all rows that have df == i
  sub_df_i = filter(sum_table_a, df == i)
  # find row(s) that has the smallest rss
  sub_df_minRSS = filter(sub_df_i, rss == min(rss))
  # if there are several rows, choose the one has the smallest lambda
  sub_add = filter(sub_df_minRSS, lambda == min(lambda))
  # add into the summary table
  sub_sum = rbind(sub_sum, sub_add)
}
rownames(sub_sum) = 1:(K + 1)

# add delta_AIC
ref = min(sub_sum$AICc)
sub_sum$delta_AICc = sub_sum$AICc - ref
round(sub_sum,1)
```


```{r}
### DRAWING THE COORDINATE PATH BY COODING
#   (the red line represent the best lambda under AICc)

fit = fusedlasso(y=w%*%y, X=w%*%X, graph = gr, gamma=1)
fit$beta <- rbind(rep(0,  dim(fit$beta)[2]), fit$beta)
fit$bls <- c(0, fit$bls)

p_matrix<- rbind(t(fit$beta), fit$bls)
x <- c(0, rev(fit$lambda))

data <- data.frame(x = rep(x, ncol(p_matrix)), 
                   value=rev(as.numeric(p_matrix)), 
                   treatment=rep(paste0('', rev(1:ncol(p_matrix))), 
                                 each=length(x)))

best_index = which(sum_table[,2] == sub_sum[which(sub_sum$delta_AICc == 0),2])

# omit lambda > 12
data <- data[which(data$x < 12), ]

# reorder the legend
data$treatment <- factor(data$treatment, levels = c(5,8,12,11,3,2,7,9,1,6,4,10))

ggplot(data = data, aes(x=x, y=value)) + 
  geom_line(aes(colour=treatment))+                            
  geom_vline(xintercept = rev(fit$lambda[-c(best_index, which(fit$lambda > 12))]),
             linetype="dashed") +
  geom_vline(xintercept = fit$lambda[best_index], linetype="dashed", color = "red") +
  xlab(expression(lambda)) + ylab("Coordinates of d")
```

```{r}
# save the coordinate path with certain requirements 
ggsave(file = "Depression_FusedLasso_multi.eps", dpi = 800, width = 10, height = 4.5, limitsize = FALSE) 
```



# Analysis with 'netmeta' package
```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = p1, sm = "MD", reference = "fluoxetine")
netgraph(net)
```

```{r}
# SUCRA values in an increasing order 
set.seed(1)
rank_ = rankogram(net)
sucra = data.frame(sort(rank_$ranking.random))
order_names = rownames(sucra)
round(sort(rank_$ranking.random),3)
```

```{r}
# The rankgram of the depression data
set.seed(1)
rank_ = rankogram(net)
plot(rank_)
```

```{r}
# the league table with given order of treatments 
t1 = netleague(net, net, digits = 2, seq = order_names)
# random effect model 
t2 = t1$random
t2
```

```{r}
# calculate the coefficient of variation of treatments 
#   in the same order of the league table
cv_t = data.frame()
for (i in 2:nrow(t2)){
  for (j in 1:(i-1)) {
    a = t2[i,j]
    results = league_str_num(a)
    cv_t[i,j] = (((league_str_num(a)[3] - 
                    league_str_num(a)[2])/4)/league_str_num(a)[1])
  }
}
round(cv_t,4)
```


```{r}
# beta values of the best model under AICc
best_index = which(sum_table[,2] == sub_sum[which(sub_sum$delta_AICc == 0),2])
ddd <- fit$beta[,best_index]
# calculate the GFL-NMA estimates of the lowest AICc model
ttt = data.frame(outer(sort(c(0,ddd), decreasing = TRUE),sort(c(0,ddd), decreasing = TRUE),"-"))
ttt
tt=round(ttt,2)
tt
```







# Save some main results for future using 


```{r}
### RUN THIS BEFORE RELOAD THE RESULTS
# Save multiple objects
save(p1, d_multi, fit, w, sum_table_a, net, file = "depression.RData")
```


# Pooled GFL-NMA
```{r}
###Code for pooled GFL-NMA###
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)
min_row = max(which(sum_table_a$AICc == min(sum_table_a$AICc)))


best_beta = fit$beta[, min_row]
t_group_list = group_dd(best_beta)

# replace the string names by num
deprn = p1[,1:5]
seq = c("fluoxetine", "bupropion", "citalopram", "duloxetine", "escitalopram",
        "fluvoxamine", "milnacipran", "mirtazapine", "paroxetine", "reboxetine",
        "sertraline", "venlafaxine")
deprn_ = data.frame(cbind(TE = deprn$TE, seTE = deprn$seTE,
                   studlab = factor(deprn$studlab, labels = 1:111),
                   t1 = match(deprn$treat1,seq), t2 = match(deprn$treat2,seq)))

update = deprn_

# rename treatments that are pooled as the smallest number in the group
for (k in 1:length(t_group_list)){
  # change t1
  c1 = sapply(deprn_$t1, contains, y = t_group_list[[k]])
  if(any(c1)){
    update$t1[which(c1)] = min(t_group_list[[k]])
  }
  # change t2
  c2 = sapply(deprn_$t2, contains, y = t_group_list[[k]])
  if(any(c2)){
    update$t2[which(c2)] = min(t_group_list[[k]])
  }
}

# drop rows that compare the same treatments (t1=t2) if any
if(length(which(update$t1 == update$t2))>0){
  update = update[-which(update$t1 == update$t2),]
}

net_i = netmeta(TE, seTE, t1, t2, studlab,data = update, sm = "MD", reference = 1)
group_i = t_group_list

############## print the result 
## TE+CI but partial
t1 = netleague(net_i,net_i, digits = 3, seq = c("5","8","11","3","2","1","6","10"))
t = t1$random
t

## one result (TE or lower or upper) per output but full
N.treat = 12
smry = summary(net_i)
# est: estimated treatment effects 
est = t_vs_ref(smry$random$TE, N.treat, group_i)


# print the estimated values (TE or corresponding 95% CI)
full_lower = data.frame(matrix(rep(0, N.treat*N.treat), nrow = N.treat))
rownames(full_lower) = colnames(full_lower) = 1:N.treat
# change smry$random$... to change the type of values 
row_names = as.numeric(rownames(data.frame(smry$random$upper)))

row_group_num = 0
for (row in 1:N.treat) {
  for (subgroup in group_i) {
    if(row %in% subgroup){row_group_num = min(subgroup)}
  }
  # no pooled group
  if(row_group_num == 0){row_group_num = row}
  col_group_num = 0
  for (col in 1:N.treat) {
    for (subgroup in group_i) {
      if(col %in% subgroup){col_group_num = min(subgroup)}
    }
    if(col_group_num == 0){col_group_num = col}
    
    c1=which(row_names == row_group_num)
    c2=which(row_names == col_group_num)
    
    full_lower[row,col] = smry$random$upper[c1,c2]
    col_group_num = 0
  }
  row_group_num = 0
}
t1 = full_lower[c(5,8,12,11,3,2,7,9,1,6,4,10),c(5,8,12,11,3,2,7,9,1,6,4,10)]
t2 = round(t1,2)*100
diag(t2) = c(5555,8888,1212,111111,3333,2222,7777,9999,1111,6666,4444,1010)
t2
```



