---
title: "Senn2013 example"
author: "Sandy Kong"
date: "2023-03-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

# Two-arm study
```{r}
data(Senn2013)
s_data = Senn2013
# remove the multi-arm rows
s_data = s_data[-c(3,27,28),]
s_data = s_data[order(s_data$studlab),]
rownames(s_data) = seq(1, nrow(s_data), 1)
s_data
```

```{r}
# factor treatment 1 and 2
s_data$treat1 = factor(s_data$treat1)
s_data$treat2 = factor(s_data$treat2)
```

```{r}
y = s_data$TE
sigma = s_data$seTE

# X ('plac' as reference)
X =  X_matrix(s_data$treat1, s_data$treat2, ref = "plac", n = 10)

w = 1/sigma
n = length(y)
K = ncol(X)
```


```{r}
e = c()
for (i in 1:9){
  for (j in (i + 1):9){
    e = append(e, c(i, j))
  }
}
e = head(e, -4)
e
```



```{r}
gr = graph(e, directed=FALSE)
# total_levels = sort(unique(c(levels(s_data$treat1), levels(s_data$treat2))))
# V(gr)$name = total_levels[-which(total_levels == "plac")]
plot(gr)
```

```{r}
# gr is needed
fit = fusedlasso(y=w*y, X=diag(w)%*%X, graph = gr, gamma=1)
fusedLasso_gr_log(fit)
```

```{r}
# from general code, step-by-step shown in the general file 

rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row(rss, Ks)]

# Calculate the rss for the full model 
mod = glm.fit(X, y, w^2, intercept = FALSE)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks)))
rownames(sum_table_a) = 1:nrow(sum_table_a)

sub_sum = data.frame()
for (i in 0:K){
  # select all rows that have df == i
  sub_df_i = filter(sum_table_a, df == i)
  # find row(s) that has the smallest rss
  sub_df_minRSS = filter(sub_df_i, rss == min(rss))
  # if there are several rows, choose the one has the smallest lambda
  sub_add = filter(sub_df_minRSS, lambda == min(lambda))
  # add into the summary table
  sub_sum = rbind(sub_sum, sub_add)
}
rownames(sub_sum) = 1:(K + 1)

# Add the weight to the sub summary table 
sub_sum$weight = exp(-0.5 * sub_sum$AICc)/sum(exp(-0.5 * sub_sum$AICc))

# add delta_AIC
ref = min(sub_sum$AICc)
sub_sum$delta_AICc = sub_sum$AICc - ref
sub_sum
```





```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = s_data, sm = "MD", reference = "plac")
netgraph(net)
```

netleague
```{r}
library(writexl)
t1 = netleague(net, net, digits = 2) # writexl=TRUE
t2 = t1$random
t2
```
rankogram
```{r, message=FALSE}
library(mvtnorm)
library(gridExtra)
```


```{r}
rank = rankogram(net)
plot(rank)
```








