---
title: "Senn2013 example"
author: "Sandy Kong"
date: "2023-03-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# clean the environment and 
rm(list = ls())
# run all helper functions
source("../Functions.R")
source("../sim_helper.R")
```

```{r}
### NEED TO RUN ALL CODE ONCE BEFORE USING
# To load the data again
load("Senn.RData")
```


# Load the data

```{r}
data(Senn2013)
```

```{r}
# find the multi arms
m_study = multi_study(Senn2013)
m_study
```

```{r}
##### Fixed Effect
# calculate the covariance
cov_Willms1999 = (0.3758^2 + 0.3579^2 - 0.4669^2) / 2
cov_Willms1999
```
```{r}
##### Random Effect
net = netmeta(TE, seTE, treat1, treat2, studlab, data = Senn2013, sm = "MD", reference = "plac")

# calculate the covariance under random effect model
cov_Willms1999 = (0.3758^2 + 0.3579^2 - 0.4669^2 + net$tau2) / 2
cov_Willms1999
```

```{r}
# keep only the 2 arms
senn_multi = Senn2013[-28,]
senn_multi[order(senn_multi$studlab),]
```


```{r}
##### Fixed Effect
# matrix with all var on diagonal
var_cov = diag((senn_multi$seTE)^2)
# find the indexes that stands for multi-arm studies 
multi_index = which(senn_multi$studlab == unique(as.vector(m_study$studlab)))
# update the cov terms in the var_cov matrix 
var_cov[multi_index[1],multi_index[2]] = cov_Willms1999
var_cov[multi_index[2],multi_index[1]] = cov_Willms1999

# better visualization
t = data.frame(var_cov)
```

```{r}
##### Random effect
# matrix with all var on diagonal
var_cov = diag((senn_multi$seTE)^2)
# Variance-covariant matrix under random effect model
var_cov = var_cov + net$tau2*diag(dim(var_cov)[1]) 
# find the indexes that stands for multi-arm studies 
multi_index = which(senn_multi$studlab == unique(as.vector(m_study$studlab)))
# update the cov terms in the var_cov matrix 
var_cov[multi_index[1],multi_index[2]] = cov_Willms1999
var_cov[multi_index[2],multi_index[1]] = cov_Willms1999
```


```{r}
# Choleski Decomposition of var_cov matrix
D = chol(solve(var_cov))

w = D
y = matrix(senn_multi$TE, nrow = length(senn_multi$TE), ncol = 1)

# X ('plac' as reference)
X =  X_matrix(senn_multi$treat1, senn_multi$treat2, ref = "plac", 
              n = 10) # n is the total number of distinct treatments
n = length(y)
K = ncol(X)
```

```{r}
# create a completed graph with 9 vertices
e = c()
for (i in 1:9){
  for (j in (i + 1):9){
    e = append(e, c(i, j))
  }
}
e = head(e, -4)
gr = graph(e, directed=FALSE)
plot(gr)
```

```{r}
### DEFAULT WAY OF DRAWING THE COORDINATE PATH
#   (the red line represents lambda where the paths are separated)
fit = fusedlasso(y=w%*%y, X=w%*%X, graph = gr, gamma=1)
fusedLasso_gr_cubic(fit)
```



# AICc summary 
```{r}
# from general code, step-by-step shown in the general file 
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)

# cubic scale
sum_table_a$lambda = sum_table_a$lambda^(1/3)

sum_table_a
```

```{r}
# create a table that only include the first row of df = 0 
#   with all other rows 
tt = data.frame(sum_table_a)[which(sum_table_a$df != 0),]
tt = rbind(sum_table_a[which(sum_table_a$df != 0)[1] - 1, ], tt)
ref = min(tt$AICc)
tt$delta_AICc = tt$AICc - ref
tt[,3:5] = round(tt[,3:5], 1)
# tt$rss = round(tt$rss, 0)
tt$lambda = round(tt$lambda, 3)
tt
```

```{r}
### DRAWING THE COORDINATE PATH BY COODING
#   (the red line represent the best lambda under AICc)

# Create a new fit_plot object with a row of 0's for ref trt
fit_plot <- fit
fit_plot$beta <- rbind(rep(0,  dim(fit_plot$beta)[2]), fit_plot$beta)
fit_plot$bls <- c(0, fit_plot$bls)
fit_plot$lambda <- (fit_plot$lambda)^(1/3)

p_matrix<- rbind(t(fit_plot$beta), fit_plot$bls)
x <- c(0, rev(fit_plot$lambda))


data <- data.frame(x = rep(x, ncol(p_matrix)), 
                   value=rev(as.numeric(p_matrix)), 
                   treatment=rep(paste0('', rev(1:ncol(p_matrix))), each=length(x)))

# reorder the legend
data$treatment <- factor(data$treatment, levels = c(1,9,8,10,3,2,5,4,6,7))

ggplot(data = data, aes(x=x, y=value)) + 
  geom_line(aes(colour=treatment))+                            
  geom_vline(xintercept = rev(fit_plot$lambda[-35]), linetype="dashed") +
  geom_vline(xintercept = fit_plot$lambda[35], linetype="dashed", color = "red") +
  xlab(expression(lambda^{frac(1, 3)})) + ylab("Coordinates of d")
```

```{r}
# save the coordinate path with certain requirements 
ggsave(file = "Senn2013_fusedLasso_multi_random.eps", dpi = 800, width = 10, height = 4.5, limitsize = FALSE)
```


# Analysis with 'netmeta' package

```{r}
net = netmeta(TE, seTE, treat1, treat2, studlab, data = Senn2013, sm = "MD", reference = "plac")
netgraph(net)
```

```{r}
# check the fixed-effect model
fit$bls
sum = summary(net)
sum$x
```



```{r}
# the league table with given order of treatments 
t1 = netleague(net, net, digits = 2, 
               seq = c("plac", "sulf","sita","vild","benf", "acar", 
                       "migl", "piog", "metf", "rosi")) 
# the random effect model
t2 = t1$random
t2
```

```{r}
# calculate the coefficient of variation of treatments 
#   in the same order of the league table
cv_t = data.frame()
for (i in 2:nrow(t2)){
  for (j in 1:(i-1)) {
    a = t2[i,j]
    # transfer the string in the league table into numbers 
    results = league_str_num(a)
    # calculate the cv
    cv_t[i,j] = ((league_str_num(a)[3] - 
                    league_str_num(a)[2])/4)/league_str_num(a)[1]
  }
}
round(cv_t,4)
```


```{r}
# beta values of the best model under AICc
ddd <- fit$beta[,35]
# calculate the GFL-NMA estimates of the lowest AICc model
ttt <- outer(sort(c(0,ddd), decreasing = TRUE),sort(c(0,ddd), decreasing = TRUE),"-")
round(ttt,2)
```



```{r}
# The rankgram of the data
set.seed(4)
rank_ = rankogram(net)
plot(rank_)
```
```{r}
# SUCRA values (round in 2 digits)
sort(round(rank_$ranking.random,4))
```



# Save some main results for future using 

```{r}
### RUN THIS BEFORE RELOAD THE RESULTS
# Save multiple objects
save(m_study, senn_multi, fit, sum_table_a, net, file = "Senn.RData")
```

# Pooled GFL-NMA
```{r}
###Code for pooled GFL-NMA###
rss = summary(fit)[,3]
Ks = summary(fit)[,1]
beta = fit$beta[, best_row_aic(rss, Ks)]

# Calculate the rss for the full model 
mod = glm(w%*%y ~ w%*%X - 1)
rss_full = deviance(mod)

# update variables 
rss = c(rss, rss_full)
Ks = c(Ks, K)

# adding the full model to the summary
sum_table = rbind(summary(fit), c(K, 0, rss_full))

# Add corresponding AICc values into the table 
sum_table_a = data.frame(cbind(sum_table, AICc = AICc_rss(rss, Ks, n)))
rownames(sum_table_a) = 1:nrow(sum_table_a)
min_row = max(which(sum_table_a$AICc == min(sum_table_a$AICc)))


best_beta = fit$beta[, min_row]
t_group_list = group_dd(best_beta)

# replace the string names by num
seq = c("plac", "acar","benf","metf","migl","piog","rosi", "sita", "sulf", "vild")
senn = data.frame(cbind(TE = Senn2013$TE, seTE = Senn2013$seTE,
                   studlab = factor(Senn2013$studlab, labels = 1:26),
                   t1 = match(Senn2013$treat1,seq), t2 = match(Senn2013$treat2,seq)))

update = senn

# rename treatments that are pooled as the smallest number in the group
c1 = sapply(senn$t1, contains, y = t_group_list[[1]])
if(any(c1)){update$t1[which(c1)] = min(t_group_list[[1]])}

c2 = sapply(senn$t2, contains, y = t_group_list[[1]])
if(any(c2)){update$t2[which(c2)] = min(t_group_list[[1]])}

# drop rows that compare the same treatments (t1=t2) if any
if(length(which(update$t1 == update$t2))>0){
  update = update[-which(update$t1 == update$t2),]
}

net_i = netmeta(TE, seTE, t1, t2, studlab,data = update, sm = "MD", reference = 1)
group_i = t_group_list

############## print the result 
## TE+CI but partial
t1 = netleague(net_i,net_i, digits = 2, seq = c("1","9","2","4","7"))
t2 = t1$random
t2

## one result (TE or lower or upper) per output but full
N.treat = 10
smry = summary(net_i)
# est: estimated treatment effects 
est = t_vs_ref(smry$random$TE, N.treat, group_i)


# print the estimated values (TE or corresponding 95% CI)
full_lower = data.frame(matrix(rep(0, N.treat*N.treat), nrow = N.treat))
rownames(full_lower) = colnames(full_lower) = 1:N.treat
# change smry$random$... to change the type of values 
row_names = as.numeric(rownames(data.frame(smry$random$TE)))

row_group_num = 0
for (row in 1:N.treat) {
  for (subgroup in group_i) {
    if(row %in% subgroup){row_group_num = min(subgroup)}
  }
  # no pooled group
  if(row_group_num == 0){row_group_num = row}
  col_group_num = 0
  for (col in 1:N.treat) {
    for (subgroup in group_i) {
      if(col %in% subgroup){col_group_num = min(subgroup)}
    }
    if(col_group_num == 0){col_group_num = col}
    
    c1=which(row_names == row_group_num)
    c2=which(row_names == col_group_num)
    
    full_lower[row,col] = smry$random$TE[c1,c2]
    col_group_num = 0
  }
  row_group_num = 0
}
t1 = full_lower[c(1,9,8,10,3,2,5,6,4,7), c(1,9,8,10,3,2,5,6,4,7)]
round(t1,2)
```
















