
```{r}
# clean the environment and 
rm(list = ls())
# run all helper functions
source("../Functions.R")
source("../sim_helper.R")
setwd("~/Desktop/codes for examples/ex7 Parkinson's diff")
```



```{r}
##### SCENARIO A.1 ##############
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, star network, homogeneity
N.treat=10
N.studies.comp=1 # studies per comparison
data1=list()
#define the treatments in the studies
t1=c(rep(1,N.studies.comp*(N.treat-1)))
t2=c()
for (j in 2:N.treat)  {t2=c(t2,rep(j,N.studies.comp))}

### simulation
for (i in 1:N.sim){ 
  if(i%%200==0){print(i)}
  
  ###generate data
  seTE=c(rep(0,N.studies.comp*(N.treat-1))) 
  TE=0
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.studies.comp*(N.treat-1),df=1)+0.5
  data1[[i]]$TE=rnorm(N.studies.comp*(N.treat-1),TE,data1[[i]]$seTE)
  #data1[[i]]$trueTE=TE
  data1[[i]]$studlab=c(1:(N.studies.comp*(N.treat-1)))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2

  ### NMA model after GFL model selection and pooled groups
  results = GLF_aicc_2arm(data1[[i]], N.treat)
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "A1.RData")
```


```{r}
load("A1.RData")
```


```{r}
# define result variables
mae = c()
mb = c()
SSresults = c()
diff_bw = c()
bw_sd = c()
diff_br = c()
br_sd = c()
n_full = 0

for (i in 1:N.sim){ 
  group_i = group[[i]]
  net_i = net[[i]]
  
  # if none or some of the treatments are pooled
  if(typeof(net_i)=="list"){
    #if not pooling any treatments, full model
    if(length(group_i)==0){n_full = 1 + n_full}
    
    smry = summary(net_i)
    
    # est: estimated treatment effects 
    est = t_vs_ref(smry$random$TE, N.treat, group_i)
    
    ### Mean Absolute Error for the Basic Parameters
    true_parameters = rep(0, N.treat - 1)
    mae[i] = mean(abs(est[-1] - true_parameters))
    
    ### Mean Bias
    mb[i] = mean(est[-1] - true_parameters)
    
    ### number of 95% CrI does not include 0
    SSresults[i] = sum(smry$random$lower > 0) 
    
    ### estimated difference between best and worst treatment
    # find the best, the worst, and the diff
    all_d = data.frame(smry$random$TE)
    diff_bw_m = 0
    for (d in 1:nrow(all_d)){
      row_max = max(all_d[d,])
      if (row_max > diff_bw_m){
        diff_bw_m = row_max
        best_t = which(all_d[d,] == row_max)
        worst_t = d
        }
    }
    diff_bw[i] = diff_bw_m
    
    ## corresponding sd
    bw_sd[i] = smry$random$seTE[best_t, worst_t]
  
    
    ### the best and reference treatment
    diff_br[i] = est[best_t]
    br_sd[i] = t_vs_ref(smry$random$seTE, N.treat, group_i)[best_t]
    
  # all treatments are pooled
  }else{
    mae[i] = mb[i] = SSresults[i] = 0
    diff_bw[i] = bw_sd[i] = diff_br[i] = br_sd[i] = 0
  }
}
```


```{r}
# mean absolute error (basic parameters)
mean(mae)
# mean bias (basic parameters)
mean(mb)
# percent of NMAs where at least one treatment effect was estimated 
#   to be non-zero with confidence
sum(SSresults>0)/N.sim 

# mean # of false positive
mean(SSresults)

# mean estimated difference between best and worst treatment
mean(diff_bw) 
# mean standard deviation for the estimated difference
mean(bw_sd) 

# mean estimated difference between best and ref treatment
mean(diff_br) 
# mean standard deviation for the estimated difference
mean(br_sd) 

# number of simulations that chose the full model
n_full
```


```{r}
##### SCENARIO A.2 ##############
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, fullz connected network, homogeneity
N.treat=10
N.studies.comp=1 # studies per comparison
data1=list()

#define the treatments in the studies
t1=c()
t2=c()
for (i in 1:(N.treat-1)){
  for (k in (i+1):N.treat){
    for(j in 1:N.studies.comp){
      t1=c(t1,i)
      t2=c(t2,k)      }}}
N.stud=length(t1)


for (i in 1:N.sim){
  if(i%%200==0){print(i)}
  seTE=c(rep(0,N.stud))
  TE=0
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.stud,df=1)+0.5
  data1[[i]]$TE=rnorm(N.stud,0,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.stud))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2
#}  
  ### NMA model after GFL model selection and pooled groups
  results = GLF_aicc_2arm(data1[[i]], N.treat)
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "A2.RData")
```

```{r}
### FULL MODEL
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, fullz connected network, homogeneity
N.treat=10
N.studies.comp=1 # studies per comparison
data1=list()

#define the treatments in the studies
t1=c()
t2=c()
for (i in 1:(N.treat-1)){
  for (k in (i+1):N.treat){
    for(j in 1:N.studies.comp){
      t1=c(t1,i)
      t2=c(t2,k)      }}}
N.stud=length(t1)


for (i in 1:N.sim){
  if(i%%200==0){print(i)}
  seTE=c(rep(0,N.stud))
  TE=0
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.stud,df=1)+0.5
  data1[[i]]$TE=rnorm(N.stud,0,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.stud))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2
  
  ### NMA model after GFL model selection and pooled groups
  results = list(list(), netmeta(TE, seTE, t1, t2, studlab,
                    data = data1[[i]], sm = "MD", reference = 1))
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "A2_full.RData")
```

```{r}
load("A2.RData")
```

```{r}
load("A2_full.RData")
```


```{r}
# define result variables
mae = c()
mb = c()
SSresults = c()
diff_bw = c()
bw_sd = c()
diff_br = c()
br_sd = c()
n_full = 0

for (i in 1:N.sim){ 
  group_i = group[[i]]
  net_i = net[[i]]
  
  # if none or some of the treatments are pooled
  if(typeof(net_i)=="list"){
    #if not pooling any treatments, full model
    if(length(group_i)==0){n_full = 1 + n_full}
    
    smry = summary(net_i)
    
    # est: estimated treatment effects 
    est = t_vs_ref(smry$random$TE, N.treat, group_i)
    
    ### Mean Absolute Error for the Basic Parameters
    true_parameters = rep(0, N.treat - 1)
    mae[i] = mean(abs(est[-1] - true_parameters))
    
    ### Mean Bias
    mb[i] = mean(est[-1] - true_parameters)
    
    ### number of 95% CrI does not include 0
    SSresults[i] = sum(smry$random$lower > 0)
    
    ### estimated difference between best and worst treatment
    # find the best, the worst, and the diff
    all_d = data.frame(smry$random$TE)
    
    diff_bw[i] = max(all_d)
    index_bw = which(all_d == max(all_d), arr.ind = TRUE)
    
    ## corresponding sd
    bw_sd[i] = smry$random$seTE[index_bw[1], index_bw[2]]
  
    
    ### the best and reference treatment
    diff_br[i] = all_d[1,index_bw[2]]
    br_sd[i] = smry$random$seTE[1, index_bw[2]]
    
  # all treatments are pooled
  }else{
    mae[i] = mb[i] = SSresults[i] = 0
    diff_bw[i] = bw_sd[i] = diff_br[i] = br_sd[i] = 0
  }
}
#save(mae, mb, SSresults, diff_bw, bw_sd, diff_br, br_sd, data1, file = "A2_smry.RData")
```

```{r}
load("A2_smry.RData")
```

```{r}
# mean absolute error (basic parameters)
mean(mae)
# mean bias (basic parameters)
mean(mb)
# percent of NMAs where at least one treatment effect was estimated 
#   to be non-zero with confidence
sum(SSresults>0)/N.sim 

# mean # of false positive
mean(SSresults)

# mean estimated difference between best and worst treatment
mean(diff_bw) 
# mean standard deviation for the estimated difference
mean(bw_sd) 

# mean estimated difference between best and ref treatment
mean(diff_br) 
# mean standard deviation for the estimated difference
mean(br_sd) 

# number of simulations that chose the full model
n_full
```
```{r}
#Exchange(GFL)
N.treat=10
N.studies.comp=1 # studies per comparison
data1=list()

#define the treatments in the studies
t1=c()
t2=c()
for (i in 1:(N.treat-1)){
  for (k in (i+1):N.treat){
    for(j in 1:N.studies.comp){
      t1=c(t1,i)
      t2=c(t2,k)      }}}
N.stud=length(t1)

for (i in 1:N.sim){
  if(i%%200==0){print(i)}
  seTE=c(rep(0,N.stud))
  TE=0
  
  group_i = group[[i]]
  
  
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.stud,df=1)+0.5
  data1[[i]]$TE=rnorm(N.stud,0,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.stud))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2
  }
```


```{r}
##### SCENARIO B.1 #######
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, star network, heterogeneity
N.treat=10
N.studies.comp=3 # studies per comparison
data1=list()
#define the treatments in the studies
t1=c(rep(1,N.studies.comp*(N.treat-1)))
t2=c()
for (j in 2:N.treat)  {t2=c(t2,rep(j,N.studies.comp))}
###generate data
tau_sq=rlnorm(N.sim,-2.56,1.74)
tau=sqrt(tau_sq)

for (i in 1:N.sim){
  if(i%%200==0){print(i)}
  #print(i)
  seTE=c(rep(0,N.studies.comp*(N.treat-1))) 
  TE_true=c(rep(0,N.studies.comp*(N.treat-1))) 
  TE=c(rep(0,N.studies.comp*(N.treat-1))) 
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.studies.comp*(N.treat-1),df=1)+0.5
  data1[[i]]$TE_true=rnorm(N.studies.comp*(N.treat-1),0,tau[i])
  data1[[i]]$TE=rnorm(N.studies.comp*(N.treat-1),data1[[i]]$TE_true,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.studies.comp*(N.treat-1)))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2

  ### NMA model after GFL model selection and pooled groups
  results = GLF_aicc_2arm(data1[[i]], N.treat)
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "B1.RData")
```

```{r}
# FULL MODEL
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, star network, heterogeneity
N.treat=10
N.studies.comp=3 # studies per comparison
data1=list()
#define the treatments in the studies
t1=c(rep(1,N.studies.comp*(N.treat-1)))
t2=c()
for (j in 2:N.treat)  {t2=c(t2,rep(j,N.studies.comp))}
###generate data
tau_sq=rlnorm(N.sim,-2.56,1.74)
tau=sqrt(tau_sq)

for (i in 1:N.sim){
  if(i%%200==0){print(i)}
  #print(i)
  seTE=c(rep(0,N.studies.comp*(N.treat-1))) 
  TE_true=c(rep(0,N.studies.comp*(N.treat-1))) 
  TE=c(rep(0,N.studies.comp*(N.treat-1))) 
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.studies.comp*(N.treat-1),df=1)+0.5
  data1[[i]]$TE_true=rnorm(N.studies.comp*(N.treat-1),0,tau[i])
  data1[[i]]$TE=rnorm(N.studies.comp*(N.treat-1),data1[[i]]$TE_true,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.studies.comp*(N.treat-1)))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2

  ### NMA model after GFL model selection and pooled groups
  results = list(list(), netmeta(TE, seTE, t1, t2, studlab,
                    data = data1[[i]], sm = "MD", reference = 1))
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "B1_full.RData")
```

```{r}
load("B1.RData")
```

```{r}
# define result variables
mae = c()
mb = c()
SSresults = c()
diff_bw = c()
bw_sd = c()
diff_br = c()
br_sd = c()
n_full = 0

for (i in 1:N.sim){ 
  group_i = group[[i]]
  net_i = net[[i]]
  
  # if none or some of the treatments are pooled
  if(typeof(net_i)=="list"){
    #if not pooling any treatments, full model
    if(length(group_i)==0){n_full = 1 + n_full}
    
    smry = summary(net_i)
    
    # est: estimated treatment effects 
    est = t_vs_ref(smry$random$TE, N.treat, group_i)
    
    ### Mean Absolute Error for the Basic Parameters
    true_parameters = rep(0, N.treat - 1)
    mae[i] = mean(abs(est[-1] - true_parameters))
    
    ### Mean Bias
    mb[i] = mean(est[-1] - true_parameters)
    
    ### number of 95% CrI does not include 0
    SSresults[i] = sum(smry$random$lower > 0)
    
    ### estimated difference between best and worst treatment
    # find the best, the worst, and the diff
    all_d = data.frame(smry$random$TE)
    
    diff_bw[i] = max(all_d)
    index_bw = which(all_d == max(all_d), arr.ind = TRUE)
    
    ## corresponding sd
    bw_sd[i] = smry$random$seTE[index_bw[1], index_bw[2]]
  
    
    ### the best and reference treatment
    diff_br[i] = all_d[1,index_bw[2]]
    br_sd[i] = smry$random$seTE[1, index_bw[2]]
    
    
  # all treatments are pooled
  }else{
    mae[i] = mb[i] = SSresults[i] = 0
    diff_bw[i] = bw_sd[i] = diff_br[i] = br_sd[i] = 0
  }
}

#save(mae, mb, SSresults, diff_bw, bw_sd, diff_br, br_sd, data1,file = "B1_smry.RData")
```

```{r}
load("B1_smry.RData")
```


```{r}
# mean absolute error (basic parameters)
mean(mae)
# mean bias (basic parameters)
mean(mb)
# percent of NMAs where at least one treatment effect was estimated 
#   to be non-zero with confidence
sum(SSresults>0)/N.sim 

# mean # of false positive
mean(SSresults)

# mean estimated difference between best and worst treatment
mean(diff_bw) 
# mean standard deviation for the estimated difference
mean(bw_sd) 

# mean estimated difference between best and ref treatment
mean(diff_br) 
# mean standard deviation for the estimated difference
mean(br_sd) 

# number of simulations that chose the full model
n_full
```




```{r}
##### SCENARIO B.2 #######
N.sim = 1000
set.seed(42)

group=list()
net=list()

#### 10 treatments, no treatment effects in the network, fully connected network, heterogeneity
N.treat=10
N.studies.comp=3 # studies per comparison
data1=list()
#define the treatments in the studies
t1=c()
t2=c()
for (i in 1:(N.treat-1)){
  for (k in (i+1):N.treat){
    for(j in 1:N.studies.comp){
      t1=c(t1,i)
      t2=c(t2,k)    }}}
###generate data
tau_sq=rlnorm(N.sim,-2.56,1.74)
tau=sqrt(tau_sq)
N.stud=length(t1)
for (i in 1:N.sim){
  if(i%%50==0){print(i)}
  
  seTE=c(rep(0,N.stud)) 
  TE_true=c(rep(0,N.stud)) 
  TE=c(rep(0,N.stud))
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.studies.comp*(N.treat-1),df=1)+0.5
  data1[[i]]$TE_true=rnorm(N.stud,0,tau[i])
  data1[[i]]$TE=rnorm(N.stud,data1[[i]]$TE_true,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.stud))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2

  
  ### NMA model after GFL model selection and pooled groups
  results = GLF_aicc_2arm(data1[[i]], N.treat)
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "B2.RData")
```

```{r}
load("B2.RData")
```

```{r}
# define result variables
mae = c()
mb = c()
SSresults = c()
diff_bw = c()
bw_sd = c()
diff_br = c()
br_sd = c()
n_full = 0

for (i in 1:N.sim){ 
  group_i = group[[i]]
  net_i = net[[i]]
  
  # if none or some of the treatments are pooled
  if(typeof(net_i)=="list"){
    #if not pooling any treatments, full model
    if(length(group_i)==0){n_full = 1 + n_full}
    
    smry = summary(net_i)
    
    # est: estimated treatment effects 
    est = t_vs_ref(smry$random$TE, N.treat, group_i)
    
    ### Mean Absolute Error for the Basic Parameters
    true_parameters = rep(0, N.treat - 1)
    mae[i] = mean(abs(est[-1] - true_parameters))
    
    ### Mean Bias
    mb[i] = mean(est[-1] - true_parameters)
    
    ### number of 95% CrI does not include 0
    SSresults[i] = sum(smry$random$lower > 0)
    
    ### estimated difference between best and worst treatment
    # find the best, the worst, and the diff
    all_d = data.frame(smry$random$TE)
    
    diff_bw[i] = max(all_d)
    index_bw = which(all_d == max(all_d), arr.ind = TRUE)
    
    ## corresponding sd
    bw_sd[i] = smry$random$seTE[index_bw[1], index_bw[2]]
  
    
    ### the best and reference treatment
    diff_br[i] = all_d[1,index_bw[2]]
    br_sd[i] = smry$random$seTE[1, index_bw[2]]
    
    
  # all treatments are pooled
  }else{
    mae[i] = mb[i] = SSresults[i] = 0
    diff_bw[i] = bw_sd[i] = diff_br[i] = br_sd[i] = 0
  }
}

#save(mae, mb, SSresults, diff_bw, bw_sd, diff_br, br_sd, data1, file = "B2_smry.RData")
```

```{r}
load("B2_smry.RData")
```


```{r}
# mean absolute error (basic parameters)
mean(mae)
# mean bias (basic parameters)
mean(mb)
# percent of NMAs where at least one treatment effect was estimated 
#   to be non-zero with confidence
sum(SSresults>0)/N.sim 

# mean # of false positive
mean(SSresults)

# mean estimated difference between best and worst treatment
mean(diff_bw) 
# mean standard deviation for the estimated difference
mean(bw_sd) 

# mean estimated difference between best and ref treatment
mean(diff_br) 
# mean standard deviation for the estimated difference
mean(br_sd) 

# number of simulations that chose the full model
n_full
```


```{r}
##### SCENARIO D #######
N.sim = 1000
set.seed(42)

group=list()
net=list()

N.treat=3
N.studies.comp=1 # studies per comparison
data1=list()
#define the treatments in the studies
t1=c()
t2=c()
for (i in 1:(N.treat-1)){
  for (k in (i+1):N.treat){
    for(j in 1:N.studies.comp){
      t1=c(t1,i)
      t2=c(t2,k)    }}}
N.stud=length(t1)
for (i in 1:N.sim){
  seTE=c(rep(0,N.stud)) 
  TE=c(rep(0,N.stud)) 
  data1[[i]]=data.frame(TE,seTE)
  data1[[i]]$seTE=0.2*rchisq(N.stud,df=1)+0.5
  data1[[i]]$TE=rnorm(N.stud,0,data1[[i]]$seTE)
  data1[[i]]$studlab=c(1:(N.stud))
  data1[[i]]$t1=t1
  data1[[i]]$t2=t2
  
  ### NMA model after GFL model selection and pooled groups
  results = GLF_aicc_2arm(data1[[i]], N.treat)
  group[[i]] = results[[1]]
  net[[i]] = results[[2]]
}

save(data1, group, net, file = "D.RData")
```

```{r}
load("D.RData")
```

```{r}
# define result variables
mae = c()
mb = c()
SSresults = c()
diff_bw = c()
bw_sd = c()
diff_br = c()
br_sd = c()
n_full = 0
N.treat=3

for (i in 1:N.sim){ 
  group_i = group[[i]]
  net_i = net[[i]]
  
  # if none or some of the treatments are pooled
  if(typeof(net_i)=="list"){
    #if not pooling any treatments, full model
    if(length(group_i)==0){n_full = 1 + n_full}
    
    smry = summary(net_i)
    
    # est: estimated treatment effects 
    est = t_vs_ref(smry$random$TE, N.treat, group_i)
    
    ### Mean Absolute Error for the Basic Parameters
    true_parameters = rep(0, N.treat - 1)
    mae[i] = mean(abs(est[-1] - true_parameters))
    
    ### Mean Bias
    mb[i] = mean(est[-1] - true_parameters)
    
    ### number of 95% CrI does not include 0
    SSresults[i] = sum(smry$random$lower > 0)
    
    ### estimated difference between best and worst treatment
    # find the best, the worst, and the diff
    all_d = data.frame(smry$random$TE)
    
    diff_bw[i] = max(all_d)
    index_bw = which(all_d == max(all_d), arr.ind = TRUE)
    
    ## corresponding sd
    bw_sd[i] = smry$random$seTE[index_bw[1], index_bw[2]]
  
    
    ### the best and reference treatment
    diff_br[i] = all_d[1,index_bw[2]]
    br_sd[i] = smry$random$seTE[1, index_bw[2]]
    
    
  # all treatments are pooled
  }else{
    mae[i] = mb[i] = SSresults[i] = 0
    diff_bw[i] = bw_sd[i] = diff_br[i] = br_sd[i] = 0
  }
}
#save(mae, mb, SSresults, diff_bw, bw_sd, diff_br, br_sd, data1,file = "D.RData")

```


```{r}
# mean absolute error (basic parameters)
mean(mae)
# mean bias (basic parameters)
mean(mb)
# percent of NMAs where at least one treatment effect was estimated 
#   to be non-zero with confidence
sum(SSresults>0)/N.sim 

# mean # of false positive
mean(SSresults)

# mean estimated difference between best and worst treatment
mean(diff_bw) 
# mean standard deviation for the estimated difference
mean(bw_sd) 

# mean estimated difference between best and ref treatment
mean(diff_br) 
# mean standard deviation for the estimated difference
mean(br_sd) 

# number of simulations that chose the full model
n_full
```





```{r}
    # find the best and the worst
    if (nrow(summary(net)$random$TE)==2){
      best_t = min(which(est!=0))
      worst_t = 1
    }else{
      for(k in 1:20){
        rank_ = rankogram_check(net)
        if(is.list(rank_)){break}
      }
      rank_order = data.frame(sort(rank_$ranking.fixed))
      names_ = as.numeric(rownames(rank_order)[c(1,nrow(rank_order))])
      worst_t = names_[1]
      best_t = names_[2]
    }
    # calculate the difference
    diff_bw[i] = est[best_t] - est[worst_t]
    
    ## corresponding sd
    # check group
    for (subgroup in group) {
      if(best_t %in% subgroup){best_t = min(subgroup)}
      if(worst_t %in% subgroup){worst_t = min(subgroup)}
    }
    # if best and the worst are in the same group
    if(best_t == worst_t){
      bw_sd[i] = 0
    }else{ 
      se_d = data.frame(smry$random$seTE)
      colnames(se_d) = rownames(se_d)
      bt_i = which(rownames(se_d)==best_t)
      wt_i = which(colnames(se_d)==worst_t)
      bw_sd[i] = smry$random$seTE[bt_i, wt_i]
      }
```










